image: docker:19.03.1

services:
  - docker:19.03.1-dind

stages:
  - build
  - deploy

step-build-image:
  only:
    - main
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/grim3212/boardgames-frontend .
    - docker push $CI_REGISTRY/grim3212/boardgames-frontend